spring.datasource.url=jdbc:mysql://localhost:3306/dutchtrip?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
spring.datasource.username=dutchtrip
spring.datasource.password=dutchtrip1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.data.redis.host=localhost
spring.data.redis.port=6379
server.port=8080
spring.security.user.name=admin
spring.security.user.password=admin1234
